[workspace]
authors = ["Kyle Shannon <kyle@kmshannon.com>"]
channels = ["conda-forge"]
name = "subiculum-lit-analysis"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
numpy = ">=2.3.4,<3"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.7,<4"
jupyterlab = ">=4.4.10,<5"
ipykernel = ">=7.1.0,<8"
pytest = ">=8.4.2,<9"
tqdm = ">=4.66.0,<5"
scipy = ">=1.11.0,<2"
